export const ActionTypes = {
    NAVIGATION_PROPS: "NAVIGATION_PROPS",

    GET_DATA_FROM_ASYNCSTORAGE: "GET_DATA_FROM_ASYNCSTORAGE",

    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",

    GET_ALL_USERS: "GET_ALL_USERS",

    GET_MESSAGES:"GET_MESSAGES",

    GET_SELECTED_USER_MESSAGES: "GET_SELECTED_USER_MESSAGES",

    GET_BLOCKED_USERS: "GET_BLOCKED_USERS",

    LATEST_MSG_SENT: "LATEST_MSG_SENT"
}