export const ActionTypes = {
    NAVIGATION_PROPS: "NAVIGATION_PROPS",

    GET_DATA_FROM_ASYNCSTORAGE: "GET_DATA_FROM_ASYNCSTORAGE",

    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",

    GET_ALL_USERS: "GET_ALL_USERS"
}